### ISSUE TITLE
Incorrect SVG rendering

### ISSUE THREAD

**Issue by PeterPanino** [viniciusfbb/skia4delphi#10]
[reactor.zip](https://github.com/viniciusfbb/skia4delphi/files/7260559/reactor.zip)

Incorrect SVG rendering of the attached SVG document in TSkSvg:

![image](https://user-images.githubusercontent.com/5140376/135483486-e65fb2a0-c0ad-4b83-a871-b963c3075958.png)

This is the correct rendering of the same SVG document in Edge browser:

![image](https://user-images.githubusercontent.com/5140376/135483726-67133533-c15d-43a3-b061-d004159d3ad9.png)

**Comment by viniciusfbb** [comment]
Hi @PeterPanino!

This is not a bug, this is a [limitation of skia svg](https://github.com/viniciusfbb/skia4delphi/blob/main/Documents/SVG.md#limitations).
`Does not support style element and style attribute` because skia does not support css.

However this is easily workable, just configure your image editor to embed the style in the attributes. We explain [how to export in Adobe Illustrator embedding style in attributes](https://github.com/viniciusfbb/skia4delphi/blob/main/Documents/SVG.md#considerations).

I exported your svg again from Adobe Illustrator without the style and the output is attached, working perfectly.
[reactor_fixed.zip](https://github.com/viniciusfbb/skia4delphi/files/7260835/reactor_fixed.zip)
