### ISSUE TITLE
Problems with Text Measuring

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [viniciusfbb/skia4delphi#24]
I am trying to draw text in the center of a box using SKIA and the values I'm getting for the measurement don't seem to be right.

Here is an example:

![image](https://user-images.githubusercontent.com/18058224/146850487-eeb54b8e-c1f9-4445-b40b-0d9222b583f1.png)

The image on the left is pure Skia -- the image on the right is an autosizing Tlabel set to use the same font/size etc. and which is then centered by its reported dimensions.  As you can see it is centered correctly while the skia one isn't .

```delphi
procedure TForm41.SkPaintBox1Draw(ASender: TObject; const ACanvas: ISkCanvas;
  const ADest: TRectF; const AOpacity: Single);
var
  Paint:ISKPaint;
  LFont1:ISkFont;
  LPaint1:ISkPaint;
  LBlob1,LBlob2:ISkTextBlob;
  LTypeface:ISkTypeface;
  TargetBoundsRect:TRectF;
  LocalScale:TPointF;
  TextToDraw:String;
  begin
  LPaint1 := TSkPaint.Create;
  LPaint1.AntiAlias := True;
  LPaint1.SetColorF(TAlphaColorF.Create(TALphaColorRec.Blue));
//draw frame around the destination rectangles
  ACanvas.DrawLine(ADest.TopLeft,PointF(0,ADest.Height),LPaint1);
  ACanvas.DrawLine(ADest.TopLeft,PointF(ADest.Width,ADest.Top),LPaint1);
  ACanvas.DrawLine(ADest.TopLeft,PointF(0,ADest.Height),LPaint1);
  ACanvas.DrawLine(PointF(ADest.Left,ADest.Height),ADest.BottomRight,LPaint1);
  ACanvas.DrawLine(PointF(ADest.Width,ADest.Height),PointF(ADest.Width,ADest.Top),LPaint1);

//create the font setup
  LTypeface := TSkTypeface.MakeFromName('Sans',tskFontStyle.Bold);
  LFont1 := TSkFont.Create(LTypeface, 18, 1);
  LFont1.Edging := TSkFontEdging.AntiAlias;
  TargetBoundsRect:=ADest;
  TextToDraw:='Skia Rules';


  if not (ASender = SkPaintBox2) then
    begin
     //if we are on the first box then lets measure the text using skia code 
      LFont1.MeasureText(TextToDraw,TargetBoundsRect,LPaint1);
      LBlob1 := TSkTextBlob.Make(TextToDraw, LFont1);
//draw the text centered based on its reported dimensions
      ACanvas.DrawTextBlob(LBlob1, (ADest.Width-TargetBoundsRect.Width)/2,(ADest.Height
      - TargetBoundsRect.Height)/2, LPaint1);
    end;

  //make a smaller font
  LFont1 := TSkFont.Create(LTypeface, 12, 1);
  LFont1.Edging := TSkFontEdging.AntiAlias;
  if ASender = SkPaintBox2 then
  begin
    //Since we are on the second box then we want to center the label based on its reported size
     Label1.SetBounds(ADest.Left+(ADest.Width-Label1.Width)/2,
       ADest.Top+(ADest.Height-Label1.Height)/2,Label1.Width,Label1.Height);
//report its bounds
     LBlob2 := TSkTextBlob.Make('Reported Bounds: '+FloatToStr(Label1.width)+'w vs '+
        FloatToStr(Label1.Height)+'h', LFont1)
  end
 else //report the Skia TExt's bounds
  LBlob2 := TSkTextBlob.Make('Reported Bounds: '+FloatToStr(TargetBoundsRect.width)+'w vs '+
     FloatToStr(TargetBoundsRect.Height)+'h', LFont1);
  ACanvas.DrawTextBlob(LBlob2, 2,(ADest.Height-18), LPaint1);
end;
```

[demo pas and fmx.zip](https://github.com/viniciusfbb/skia4delphi/files/7748731/demo.pas.and.fmx.zip)

**Comment by viniciusfbb** [comment]
@TheOriginalBytePlayer What is your screen scale?

**Comment by TheOriginalBytePlayer** [comment]
![image](https://user-images.githubusercontent.com/18058224/146854073-21f22c28-ba6e-4ff7-8e4b-09d9fe815eff.png)

**Comment by viniciusfbb** [comment]
@TheOriginalBytePlayer The code is working as it should. The TargetBoundsRect.Top is -14 and TargetBoundsRect.Bottom is 0.

In MeasureText(), the y coordinates is relative to the baseline, which is neither above nor below the font, but usually strikes it somewhere across the middle. For this reason the bounds rectangle will have (usually) a negative top and a positive bottom. The negative top means that the top of the text is above the baseline (y decreases going up), while the positive bottom means that the bottom of the text is below the baseline (y increases going down).

So, after MeasureText() line, you can simple use TargetBoundsRect.Offset(0, -TargetBoundsRect.Top);

Since you are rendering texts, I would like to give a tip. The ACanvas.DrawTextBlob or ACanvas.DrawSimpleText are primitive forms of drawing text. Skia has developed a module for advanced texts called SkParagraph, which I recommend. Also, in a few weeks we will release version 3 with the new control TSkLabel, that uses SkParagraph to render the text.

**Comment by viniciusfbb** [comment]
**Fix:** Although MeasureText() is returning the top negative, it is not influencing your code as you are using TargetBoundsRect.Height. Your problem is occurring because Canvas.DrawTextBlob() and Canvas.DrawSimpleText() also consider the y coordinates where 0 is the base of the line.

The library code continues to work as intended, but just to be more precise, your code that would need to be adapted is just the line:

```delphi
  ACanvas.DrawTextBlob(LBlob1, (ADest.Width-TargetBoundsRect.Width)/2,(ADest.Height - TargetBoundsRect.Height)/2, LPaint1);
```

replacing to:

```delphi
  ACanvas.DrawTextBlob(LBlob1, (ADest.Width-TargetBoundsRect.Width)/2,((ADest.Height - TargetBoundsRect.Height)/2) - TargetBoundsRect.Top, LPaint1);
```

**Comment by TheOriginalBytePlayer** [comment]
Brilliant.  That solves my problem completely, though I must confess it is hardly intuitive.  I am also not sure what the advantages is of returning the values in that manner, even if that is Skia's native way of doing things.  

Given that this is a delphi wrapper, I expect it to translate the code to the delphi style of working and  I personally think it would be more useful to Delphi programmers to return normalized values making it more equivalent to .  You could split it to two functions 

**MeasureText** which returns normalized values and 
**MeasureTextNativeSkia** which returns the Skia Style values

**Comment by viniciusfbb** [comment]
The implementation of the way they did it has its benefits because knowing the position of the base of the line can help some drawings, for example, to draw a line underlining the text... Our purpose is to be very close to the original skia, so for now let's keep it the way it is.

However, if you use SkParagraph you will avoid these problems as it works with normalized positions (and not the base of the line), then it is a good alternative.
