### ISSUE TITLE
Extend Components like FMX?

### ISSUE THREAD

**Issue by PonyPC** [viniciusfbb/skia4delphi#5]
This is a great project, I wonder if this can replace fmx components in delphi development.

**Comment by viniciusfbb** [comment]
Hi @PonyPC,

Skia is a lib for drawing and manipulating images. The idea is not to replace the components, the correct thing would be to replace firemonkey's TCanvas by a skia canvas, but this is not our current focus.

That's not to say we won't create components, because in this week's update we'll add 3 visual components for VCL and FMX: TSkPaintBox, TSkSVGViewer, TSkLottieAnimation.

But the focus now is to improve the api, making it simpler and easier to use, fixing minor bugs and doing unit tests.

**Comment by danieleteti** [comment]
Keep the good work guys!

**Comment by PonyPC** [comment]
Thanks for your great job. Wish delphi to have an efficient ui framework like Chrome.
